domain: "https://vaultwarden.rafa.run"
image:
  tag: "1.32.0-alpine"
signupsAllowed: false
resourceType: "Deployment"
timeZone: "Europe/Berlin"
ingress:
  enabled: false
adminToken:
  existingSecret: "vaultwarden-admin-token"
  existingSecretKey: "token"
data:
  name: "vaultwarden-data"
  size: "10Gi"
  path: "/data"
  accessMode: "ReadWriteOnce"