# https://www.suse.com/c/rancher_blog/using-minio-as-backup-target-for-rancher-longhorn-2/
apiVersion: v1
kind: Secret
metadata:
  name: s3-secret
  namespace: longhorn-system
type: Opaque
data:
  AWS_ACCESS_KEY_ID: 123 # Base64
  AWS_SECRET_ACCESS_KEY: 123 # Base64
  AWS_ENDPOINTS: 123 # Base64