---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gameserver-rafa-run
  namespace: petrodactyl # Change this to the namespace where the application is
spec:
  secretName: gameserver-rafa-run-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.gameserver.rafa.run"
  dnsNames:
  - "gameserver.rafa.run"
  - "*.gameserver.rafa.run"