---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: rafa-run
  namespace: default # Change this to the namespace where the application is
spec:
  secretName: rafa-run-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: "*.rafa.run"
  dnsNames:
  - "rafa.run"
  - "*.rafa.run"