- name: Ensure /usr/local/bin exists
  ansible.builtin.file:
    path: /usr/local/bin/
    state: directory
- name: Ensure script file exists
  ansible.builtin.copy:
    src: forwarding.sh
    dest: /usr/local/bin/forwarding.sh
    force: true
    group: root
    owner: root
    mode: 0755