kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pelican-data-claim
  namespace: pelican
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi