kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pterodactyl-mariadb-claim
  namespace: pterodactyl
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi