- name: Enable net.ipv4.ip_forward
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: '1'
    sysctl_set: true
    state: present
    reload: true
- name: Disable ufw
  shell: ufw disable
- name: Disable ufw service
  ansible.builtin.systemd_service:
    name: ufw
    enabled: false
    masked: yes
- name: Install nftables
  ansible.builtin.apt:
    name: nftables
- name: Enable nftables service
  ansible.builtin.systemd_service:
    name: nftables
    state: started
    enabled: true
    masked: no