apiVersion: v1
kind: Secret
metadata:
  name: pterodactyl-panel
  namespace: pterodactyl
type: Opaque
data:
  DB_PASSWORD: some-base-64-encoded-password
  REDIS_PASSWORD: some-base-64-encoded-password
