- hosts: fservers
  become: true
  roles:
    - role: setup_nftables
    - role: reset_nft_rules

- hosts: public
  become: true
  roles:
    - role: forward_tcp
      self_address: "{{ ansible_host }}"
      forward_port: 25565 # Change
      target_server: "{{ hostvars[groups['private'][0]]['tailscale_address'] }}"

- hosts: private
  become: true
  roles:
    - role: forward_tcp
      self_address: "{{ tailscale_address }}"
      forward_port: 25565 # Change
      target_server: "192.168.0.146" # Change