- name: Check if MASQUERADE rule exists
  ansible.builtin.lineinfile:
    path: /usr/local/bin/forwarding.sh
    regexp: '^iptables -t nat -A POSTROUTING -j MASQUERADE'
    line: iptables -t nat -A POSTROUTING -j MASQUERADE
    insertbefore: '^# Generated end'
- name: Add debug message
  ansible.builtin.lineinfile:
    path: /usr/local/bin/forwarding.sh
    line: "echo 'Adding forwarding rule for UDP packets from 127.0.0.1:{{ source_port }} to {{ target_server }}:{{ forward_port }}'"
    insertbefore: '^# Generated end'
- name: Add forwarding rule
  ansible.builtin.lineinfile:
    path: /usr/local/bin/forwarding.sh
    line: iptables -t nat -A PREROUTING -p udp --dport {{ source_port }} -j DNAT --to-destination {{ target_server }}:{{ forward_port }}
    insertbefore: '^# Generated end'
- name: Create ipv6 tunnel
  ansible.builtin.lineinfile:
    path: /usr/local/bin/forwarding.sh
    line: nohup socat UDP6-LISTEN:{{ source_port }},fork UDP4:{{ target_server }}:{{ forward_port }} &
    insertbefore: '^# Generated end'
  when: ipv6 == true